# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
set:
  - pipefail
shopt:
  - globstar
includes:
  build: .taskfiles/build/Taskfile.yaml
  bootstrap: .taskfiles/bootstrap/Taskfile.yaml
tasks:
  default:
    silent: true
    cmd: task --list
